name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for Gradle caching
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Validate Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Generating Gradle Wrapper..."
            gradle wrapper --gradle-version 8.2.1
          fi
          chmod +x gradlew
          
      - name: Cache Gradle
      uses: actions/cache@v3
  with:
    path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    restore-keys: |
      ${{ runner.os }}-gradle-
          
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2.1
          arguments: |
            clean
            assembleDebug
            -Pandroid.useAndroidX=true
            -Pandroid.enableJetifier=true
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error